version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: ./Server
    container_name: server
    env_file: .env
    ports:
      - "1234:1234"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: 1234
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      NODE_ENV: production
    depends_on:
      - postgres

  client:
    build:
      context: ./Client
    container_name: client
    env_file: .env
    ports:
      - "3000:80"
    depends_on:
      - server

volumes:
  postgres_data:
